image:
  name: daym/guix-on-docker

build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

test-job2021-1:
  stage: test
  script:
    - guix environment --ad-hoc sbcl --load "2021/2021.lisp" --eval "(1a \"2021/1_data.txt\")"
