variables:
  QUICKLISP_ADD_TO_INIT_FILE: "true"

image:
  name: clfoundation/sbcl:latest

before_script:
  - install-quicklisp

build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

test-job2021-1:
  stage: test
  script:
    - sbcl --load "2021/2021.lisp" --eval "(1a \"2021/1_data.txt\")"
