(define (day1-1 elf-counts)
  (let ((count-list (string-split elf-counts #\newline)))
    (let reduce ((to-count count-list) (max-elf 0) (current-elf 0))
      (if (null? to-count)
          (max max-elf current-elf)
          (let* ((current-count (car to-count))
                 (parsed (string->number current-count)))
            (cond ((= 0 (string-length current-count))
                   (reduce (cdr to-count) (max current-elf max-elf) 0))
                  (parsed (reduce (cdr to-count) max-elf (+ current-elf parsed)))
                  (#t (error (string-append "Unable to parse number: " current-count)))))))))
